*** empty log message ***
git-svn-id: https://openmodelica.org/svn/OpenModelica/trunk@269 f25d12d1-65f4-0310-ae8a-bbce733d8d8e

diff --git a/modeq/testsuite/Makefile b/modeq/testsuite/Makefile
--- a/modeq/testsuite/Makefile
+++ b/modeq/testsuite/Makefile
@@ -1,7 +1,23 @@
 
 
 all :
-	for f in *.mdc; do \
+	@echo
+	@echo The following teste should not cause any errors
+	@echo
+	@-for f in *-s-*.mo; do \
+	  tmp=/tmp/modeq-test-$$$$; \
 	  echo testing $$f; \
-	  ../modeq $$f 2>&1 | egrep '^#|Execution failed!'; \
+	  ../modeq $$f >$$tmp 2>&1; \
+	  [ $$? -ne 0 ] || egrep '^#|Execution failed!' $$tmp && \
+		( echo FAILURE! Log saved in /tmp/log-$$f ; \
+		  mv $$tmp /tmp/log-$$f ); \
 	done
+	@echo
+	@echo The following teste should fail
+	@echo
+	@-for f in *-f-*.mo; do \
+	  echo testing $$f; \
+	  (../modeq $$f 2>&1 && echo '! Succeeded') \
+		| egrep '^#|!|Execution failed!'; \
+	done
+
